name: Access SDK
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - master
    paths:
      - 'packages/access/**'
      - '.github/workflows/access.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/access/**'
      - '.github/workflows/access.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter @web3-storage/access run lint
      - run: pnpm -r --filter @web3-storage/access run test
