name: Manual Deploy
on:
  workflow_dispatch:
jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.x
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/packages/website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('packages/website/**.[jt]s', 'packages/website/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - run: pnpm install
      - run: pnpm -r --filter website run build
      - run: npx wrangler pages publish --project-name ucan-protocol --branch master ./packages/website/out
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
